#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

export DJANGO_SETTINGS_MODULE='config.settings.{{ project_name }}_admin.production'

/usr/local/bin/gunicorn -w 2 -b :5000 --chdir=/app config.wsgi
