version: '3'

volumes:
  local_postgres_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: dockerfiles/local/Dockerfile
    image: {{ project_name }}_local_api
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:9.6
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

  redis:
    image: redis:3.2

  celeryworker:
    <<: *django
    image: {{ project_name }}_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: {{ project_name }}_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: {{ project_name }}_local_flower
    ports:
      - "5555:5555"
    command: /start-flower

  admin:
    <<: *django
    image: {{ project_name }}_local_admin
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8001:8001"
    command: /start-admin
